CREATE SCHEMA `test` DEFAULT CHARACTER SET utf8;

CREATE TABLE `test`.`user` (
`ID` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
`NAME` VARCHAR(25) NOT NULL,
`AGE` INT NOT NULL,
`IS_ADMIN` BIT(1) NOT NULL DEFAULT false,
`CREATED_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO `test`.`user` (`NAME`, `AGE`) VALUES ('Vlad', '25');
INSERT INTO `test`.`user` (`NAME`, `AGE`) VALUES ('Jonn', '10');
INSERT INTO `test`.`user` (`NAME`, `AGE`) VALUES ('Danny', '35');
